image:
  file: Dockerfile
tasks:
    - init: pnpm install
      command: pnpm dev
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
