#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm commitlint --edit $1

echo "Committed as:"
echo "  (use \"git reset --soft HEAD^\" to undo)\n"
echo "   \033[1;93m`git config --local user.name` <`git config --local user.email`>\033[00m\n"
echo "\033[1;95mCheck if they are correct\033[00m\n"
