#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -z "`git config --local user.name`" ]; then
  echo "fatal: user.name is not set locally"
  exit 1
fi

if [ -z "`git config --local user.email`" ]; then
  echo "fatal: user.email is not set locally"
  exit 1
fi

# pnpm lint-staged
echo "Running pre-commit hook"
